name: Build and Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-2019
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Project
        run: msbuild Fingemulator.sln /p:Configuration=Release

      - name: Create GitHub Release and Upload Executable
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generateReleaseNotes: true
          artifacts: x64/Release/Fingemulator.exe
          artifactContentType: application/octet-stream
